name: currency_converter
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http:
  provider:
  shared_preferences:
  device_preview: ^1.0.0
  flutter_timer_countdown: ^1.0.5
  lottie: ^2.6.0
  firebase_auth: ^4.15.3
  firebase_core: ^2.26.0
  google_sign_in: ^5.2.1
  cloud_firestore: ^4.14.0
  firebase_messaging: ^14.7.19
  flutter_local_notifications: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
    android:
      generate: true
    image_path: "assets/icon.png"


flutter:
  uses-material-design: true

  
  assets:
    - assets/images/watch-3.png
    - assets/images/watch-4.png
    - assets/images/vector-1.png
    - assets/images/vector-2.png
    - assets/images/vector-3.png
    - assets/images/login-2.png
    - assets/images/login-1.png
    - assets/images/signup-2.png
    - assets/images/logo.png
    - assets/images/logo2.png