// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMk37zNwhv540tq2eb0ftBC7FuzOSy0EU',
    appId: '1:996139056388:web:c48d984d341dd2a9c5e451',
    messagingSenderId: '996139056388',
    projectId: 'currencyconverter-87c6a',
    authDomain: 'currencyconverter-87c6a.firebaseapp.com',
    storageBucket: 'currencyconverter-87c6a.appspot.com',
    measurementId: 'G-5WH0E7GC9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqm4tEDWyokJ8KJg5ySQumd_mMSvw8vuE',
    appId: '1:996139056388:android:c1aaf0e748f152a3c5e451',
    messagingSenderId: '996139056388',
    projectId: 'currencyconverter-87c6a',
    storageBucket: 'currencyconverter-87c6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtUUEvjV5iynGcbs3-Ihd5BxeTHAwnHrs',
    appId: '1:996139056388:ios:f0d77633c51f13e6c5e451',
    messagingSenderId: '996139056388',
    projectId: 'currencyconverter-87c6a',
    storageBucket: 'currencyconverter-87c6a.appspot.com',
    iosBundleId: 'com.example.currencyConverter',
  );
}
